services:
  Api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    image: noteshare_api
    container_name: noteshare_api_container 
    env_file: .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    container_name: db_postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: NoteShareDB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d NoteShareDB"]
      interval: 2s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: